field: 50341572-0729-46c9-8462-e8a0e1713d78 # Columns
fieldLayouts:
  82e29f6b-6d00-46cb-a11a-2a694288b2e8:
    tabs:
      -
        elements:
          -
            fieldUid: f65098e0-78ff-40fa-a3ae-0606327fbbdb # Column Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7fc1f3f4-c539-4af0-ac1b-0a863ed96ab5 # External Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2935bf9c-4a64-42b5-89e4-a0f209960804 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 53f1f89d-f889-4274-a901-b8e85322153a # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7fc1f3f4-c539-4af0-ac1b-0a863ed96ab5: # External Url
    contentColumnType: string(255)
    fieldGroup: null
    handle: externalUrl
    instructions: ''
    name: 'External Url'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
        - tel
        - email
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  53f1f89d-f889-4274-a901-b8e85322153a: # Video
    contentColumnType: string
    fieldGroup: null
    handle: video
    instructions: ''
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:22d349b2-38e8-409e-9b10-f2f9e5f44679' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:c60d6241-6385-4399-9478-a11d43dc642d' # Videos
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:c60d6241-6385-4399-9478-a11d43dc642d' # Videos
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  2935bf9c-4a64-42b5-89e4-a0f209960804: # Icon
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: ''
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:e48b0054-7c21-4d7b-9ad9-461d1736b58c' # Icons
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:e48b0054-7c21-4d7b-9ad9-461d1736b58c' # Icons
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:e48b0054-7c21-4d7b-9ad9-461d1736b58c' # Icons
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f65098e0-78ff-40fa-a3ae-0606327fbbdb: # Column Title
    contentColumnType: text
    fieldGroup: null
    handle: columnTitle
    instructions: ''
    name: 'Column Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: column
name: Column
sortOrder: 1
